baseURL: 'https://bcinternals.com/'
languageCode: 'en-us'
title: 'BC Internals'
theme: "anubis"
googleAnalytics: "G-QQFBZ4CYWE"
enableRobotsTXT: true

params:
  author: "Mads Gram"
  email: "mgmadsgram<AT>gmail.com"
  dateFormat: "2006-01-02"
  style: "auto-without-switcher"

  social:
    - id: github
      name: phduck/ALBlog_go
    - id: twitter
      name: Phduck2
    - id: linkedin
      name: mads-gram
